<a href="https://colab.research.google.com/github/Lmaga0320/Clase-6/blob/main/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Metodos basicos y operaciones sobre un DataFrame

Trabajemos los principales metodos de un DateFrame y las pricipales operaciones que podemos aplicarsobre este tipo de dato y que resultaran utiles en los proyectos que desarrollemos:

En participar veremos:

1. Metodos que nos permita obtener informacion general de un DataFrame
2. Metodos para realizar operaciones matematicas y de sintesis (summarization) de un DataFrame
3. El metodo apply, que nos permiteaplicar cualquier tipode funcion del DataFrame

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/peliculas.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   object
 1   director_name              4814 non-null   object
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object
 10  actor_1_name               4909 non-null   object
 11  movie_title                4916 non-null   object
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   object
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   object
 17  movie_imdb_link            4916 non-null   object
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4902 non-null   object
 20  country                    4911 non-null   object
 21  content_rating             4616 non-null   object
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

Identifico que en la columna 3 de df de un total 4916, en esta columna se encuentran 4901, demostrando que hay 15 campos sin informacion o en esta nam.

Estos metodos que vamos a utilizar head(), tai(), y sample () nos permite imprimir en pantalla las primeras filas de Dataframe, las ultimas o una seleccion aleatoria de filas, respectivamente.

In [ ]:
df.head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [ ]:
# head: sin argumentos imprime las primeras 5 filas del DateFrame. y con argumentos las que yo necesite (cantidad de lo que necesito)
df.head()

df.head(15)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000

In [ ]:
df.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [ ]:
df.tail(7)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [ ]:
# con esta linea de codigo me muestra las ultimas 5 () y con argumentos lo que yo necesito.

In [ ]:
# este metodo sirve para enteder mejor como estan distribuidos nuestros datos
df.sample()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4586,Color,Christopher Scott Cherot,25.0,84.0,21.0,48.0,Robinne Lee,465.0,2301777.0,Comedy,...,36.0,English,USA,R,650000.0,1997.0,170.0,6.5,NaN,161

In [ ]:
df.sample(4)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1739,Color,David Wain,173.0,101.0,136.0,526.0,Ken Marino,833.0,67266300.0,Comedy,...,170.0,English,Germany,R,28000000.0,2008.0,543.0,6.9,1.85,0
4760,Color,Tom Seidman,4.0,98.0,3.0,104.0,Derek Brandon,337.0,NaN,Drama|Family,...,10.0,English,USA,PG,250000.0,2010.0,168.0,6.2,NaN,0
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
2008,Color,Terry Gilliam,84.0,137.0,0.0,161.0,David Hyde Pierce,12000.0,41895491.0,Comedy|Drama|Fantasy,...,170.0,English,USA,R,24000000.0,1991.0,443.0,7.6,1.85,12000

In [ ]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

### En resumen en esta linea de codigo nos simplifica los datos estadisticos
#nombre de columnas numericas
#conteo:cuantos datos no faltantes (cuantos datos hay en cada columna)
#mediana:promedio de esos datos no faltantes
#desviacion estandar
#valor minimo
#primer cuartil
#segundo cuartil
#tercer cuartil
#valor **maximo**
#Eso me va a permitir tener una idea de mi general de como esta distribuido
#nuestros datos, pero sera mas facil de enteder con herramientas graficas
## con Matplotlib-seaborn

El metodo value_counts() tambien resulta util pues permite imprimir en pantalla el conteo de valores presentes en cada columna. Funciona tanto para variables numericas como categoricas, aunque resulta mas util en el caso de variable categoricas:

In [ ]:
#value_counts para la columna numerica(duration)
df['duration'].value_counts()

duration
90.0     160
100.0    137
98.0     135
101.0    132
97.0     131
        ...
58.0       1
35.0       1
59.0       1
62.0       1
47.0       1
Name: count, Length: 191, dtype: int64

In [ ]:
#Voy a la columna duracion ya que es uan columna numerica
#Por cada uno de esos valores que hay en esa columna
#Hay 160 peliculas con una duracion de 90 minutos
#Hay 137 peliculas con una duracion de 100 minutos
#Con estos datos podemos realizar un Histrograma dela distribucion de estos datos
#Pero est lo realizaremos em Matplotlib

In [ ]:
df['color'].value_counts()

color
Color              4693
Black and White     204
Name: count, dtype: int64

In [ ]:
#imprime los diferentes niveles que tiene esa variable categorica
#hay 4693 peliculas a color
#hay 204 pelicuals a blanco y negro
#es una manera rapida de ver los diferentes niveles que puede tener
#una variable categorica

2. Operaciones matematicas y de sintesis

Pandas contiene varios metodos que usan operaciones matematicas para resumir una columna o una fila. Estos metodos funcionan unicamente en las columanas con datos numericos.

Los ,as usados son:

* min() y max(): calcual el minimo /maximo de cada fila o columna
* sum() : calcual la suma de los elementos de cada fila o columna
* mean(), std, median():calcula la media /desviacion estandar /mediana de cada fila o columna.

Por defecto estas operaciones se aplican sobre las columnas (axis = 1)pero si definimos axis = 0 el calculo se hara por filas:

Haz doble clic (o pulsa Intro)para editar

In [ ]:
#calcular el minimo de cada columna  RESULTADO DE LA EXPLICACION ANTERIOR
df.min()

TypeError: '<=' not supported between instances of 'str' and 'float'

In [ ]:
df.select_dtypes(include='number').min() # y probar con max(), sum(), mean(), std()

num_critic_for_reviews          1.00
duration                        7.00
director_facebook_likes         0.00
actor_3_facebook_likes          0.00
actor_1_facebook_likes          0.00
gross                         162.00
num_voted_users                 5.00
cast_total_facebook_likes       0.00
facenumber_in_poster            0.00
num_user_for_reviews            1.00
budget                        218.00
title_year                   1916.00
actor_2_facebook_likes          0.00
imdb_score                      1.60
aspect_ratio                    1.18
movie_facebook_likes            0.00
dtype: float64

In [ ]:
df.select_dtypes(include='number').max() # y probar con max(), sum(), mean(), std()

num_critic_for_reviews       8.130000e+02
duration                     5.110000e+02
director_facebook_likes      2.300000e+04
actor_3_facebook_likes       2.300000e+04
actor_1_facebook_likes       6.400000e+05
gross                        7.605058e+08
num_voted_users              1.689764e+06
cast_total_facebook_likes    6.567300e+05
facenumber_in_poster         4.300000e+01
num_user_for_reviews         5.060000e+03
budget                       4.200000e+09
title_year                   2.016000e+03
actor_2_facebook_likes       1.370000e+05
imdb_score                   9.500000e+00
aspect_ratio                 1.600000e+01
movie_facebook_likes         3.490000e+05
dtype: float64

In [ ]:
df.select_dtypes(include='number').sum() # y probar con max(), sum(), mean(), std()

num_critic_for_reviews       6.715920e+05
duration                     5.248520e+05
director_facebook_likes      3.326544e+06
actor_3_facebook_likes       3.088835e+06
actor_1_facebook_likes       3.188144e+07
gross                        1.931509e+11
num_voted_users              4.062825e+08
cast_total_facebook_likes    4.709438e+07
facenumber_in_poster         6.753000e+03
num_user_for_reviews         1.310239e+06
budget                       1.619785e+11
title_year                   9.631773e+06
actor_2_facebook_likes       7.952291e+06
imdb_score                   3.164640e+04
aspect_ratio                 1.020058e+04
movie_facebook_likes         3.612421e+07
dtype: float64

La forma más sencilla de sumar todos los valores de un dataframe de Pandas es usar el método sum() . Este método calcula la suma de cada columna del dataframe y devuelve un nuevo dataframe con los resultados

In [ ]:
df.select_dtypes(include='number').mean() # y probar con max(), sum(), mean(), std()

num_critic_for_reviews       1.379889e+02
duration                     1.070908e+02
director_facebook_likes      6.910145e+02
actor_3_facebook_likes       6.312763e+02
actor_1_facebook_likes       6.494488e+03
gross                        4.764451e+07
num_voted_users              8.264492e+04
cast_total_facebook_likes    9.579816e+03
facenumber_in_poster         1.377320e+00
num_user_for_reviews         2.676688e+02
budget                       3.654749e+07
title_year                   2.002448e+03
actor_2_facebook_likes       1.621924e+03
imdb_score                   6.437429e+00
aspect_ratio                 2.222349e+00
movie_facebook_likes         7.348294e+03
dtype: float64

Mean: devuelve un valor numérico que se aproxima al promedio aritmético de sus argumentos. El tipo de función es numérico.

In [ ]:
df.select_dtypes(include='number').std() # y probar con max(), sum(), mean(), std()

num_critic_for_reviews       1.202394e+02
duration                     2.528602e+01
director_facebook_likes      2.832954e+03
actor_3_facebook_likes       1.625875e+03
actor_1_facebook_likes       1.510699e+04
gross                        6.737255e+07
num_voted_users              1.383222e+05
cast_total_facebook_likes    1.816432e+04
facenumber_in_poster         2.023826e+00
num_user_for_reviews         3.729348e+02
budget                       1.002427e+08
title_year                   1.245398e+01
actor_2_facebook_likes       4.011300e+03
imdb_score                   1.127802e+00
aspect_ratio                 1.402940e+00
movie_facebook_likes         1.920602e+04
dtype: float64

la función std() en pandas obtiene la desviación estándar de los valores de un eje especificado de un DataFrame dado. Matemáticamente, La desviación estándar se define como la medida de la dispersión de cada valor de un conjunto de datos con respecto a la media.